Refactoring files into modules by action
diestrin/btc-simulation pull request #5
Opened 2017-09-16 19:37 UTC by diestrin

2017-09-16 19:37 UTC, diestrin commented
Use `Squash and merge` if everything looks good please

2017-09-17 01:59 UTC, ecairol approved these changes

2017-09-19 00:00 UTC, jrgherrera commented on src/state.js
> +      tradeRate, result, feeInBase,
transaction method does not receive a property called feeInBase, it receives a property called fee

2017-09-19 00:01 UTC, jrgherrera requested changes
Please fix the property in the transaction call

2017-09-19 00:10 UTC, diestrin commented
@jrgherrera sir yes sir, work is done :)

2017-09-19 00:18 UTC, jrgherrera approved these changes

2017-09-19 00:20 UTC, merged